spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      auto-offset-reset: earliest
      group-id: my-group
      properties:
        enable.auto.commit: true
        auto.commit.interval.ms: 10000 # Commit every 10 seconds
  data:
    redis:
      host: redis
      port: 6379