name: CI/CD
on:
  push:
  pull_request:
    types:
      - opened
  workflow_dispatch: # allow manual execution

env:
  DOCKER_BUILDKIT: 1 # use the new docker build backend

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build images
        run: |
          docker build -f Containerfile -t rouhim/beatport-to-spotify:latest .

      - name: Run Trivy vulnerability scanner on docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'rouhim/beatport-to-spotify'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Push images
        if: github.ref_name == 'main' # only push the image if the branch is main
        run: |
          docker login
          docker push rouhim/beatport-to-spotify:latest